apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: go-drive

resources:
  - namespace.yaml
  - postgres-configmap.yaml
  - postgres-statefulset.yaml
  - configmap.yaml
  - secret.yaml
  - user-service-deployment.yaml
  - api-gateway-deployment.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: go-drive
  app.kubernetes.io/part-of: go-drive
